In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Try using Kenway's Test data (Poor Results)

In [6]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression



# Load the dataset
file_path = 'Resources/Kenways_ML_Test.csv'
df = pd.read_csv(file_path, low_memory=False)

# Drop columns with too many missing values
df.drop(columns=['End_Lat', 'End_Lng'], inplace=True)

# Handle missing values in other columns
df.dropna(inplace=True)

# Convert date columns to datetime and then to numerical values (e.g., ordinal)
df['Weather_Timestamp'] = pd.to_datetime(df['Weather_Timestamp']).map(pd.Timestamp.toordinal)

# Create labels and features
y = df['Severity']
X = df.drop(columns=['Severity'])

# Identify non-numeric columns
non_numeric_columns = X.select_dtypes(include=['object']).columns

# One-hot encode categorical columns
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Instantiate and fit the Logistic Regression model
clf = LogisticRegression(random_state=1, max_iter=1000)
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Combine classes into binary categories
df['binary_target'] = df['Severity'].apply(lambda x: 0 if x in [1, 2] else 1)

# Features and new binary target
X = df.drop(columns=['Severity', 'binary_target'])
y = df['binary_target']

# One-hot encode categorical columns again
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train the logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

[[  0  98   0   0]
 [  0 374   0   0]
 [  0 109   0   0]
 [  0  45   0   0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        98
           2       0.60      1.00      0.75       374
           3       0.00      0.00      0.00       109
           4       0.00      0.00      0.00        45

    accuracy                           0.60       626
   macro avg       0.15      0.25      0.19       626
weighted avg       0.36      0.60      0.45       626

Confusion Matrix:
 [[562   0]
 [189   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.75      1.00      0.86       562
           1       0.00      0.00      0.00       189

    accuracy                           0.75       751
   macro avg       0.37      0.50      0.43       751
weighted avg       0.56      0.75      0.64       751



# Use highly Correlated Colums (Poor results)

In [9]:
# Load the dataset
file_path = 'Resources/US_Accidents_2022_Phoenix_Metro2.csv'
df = pd.read_csv(file_path, low_memory=False)

# Drop columns with too many missing values
df.drop(columns=['End_Lat', 'End_Lng'], inplace=True)

# Handle missing values in other columns
df.dropna(inplace=True)

# Convert date columns to datetime and then to numerical values (e.g., ordinal)
df['Accident_Date'] = pd.to_datetime(df['Accident_Date']).map(pd.Timestamp.toordinal)

# Create labels and features
y = df['Severity']
X = df.drop(columns=['Severity'])

# Identify non-numeric columns
non_numeric_columns = X.select_dtypes(include=['object']).columns

# One-hot encode categorical columns
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Combine classes into binary categories
df['binary_target'] = df['Severity'].apply(lambda x: 0 if x in [1, 2] else 1)

# Features and new binary target
X = df.drop(columns=['Severity', 'binary_target'])
y = df['binary_target']

# One-hot encode categorical columns again
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)


In [10]:
# One-hot encode categorical columns
df_encoded = pd.get_dummies(df, columns=non_numeric_columns, drop_first=True)

# Compute correlation between features and target variable
correlation = df_encoded.corr()['binary_target'].abs().sort_values(ascending=False)

# Display correlation values 1 - 10
print(correlation[1:11])

Severity                                                                               0.886905
Description_Lane blocked due to crash on I-17 Southbound at AZ-101-LOOP.               0.185686
Street_N Black Canyon Hwy                                                              0.181479
Street_I-10 W                                                                          0.172292
Street_I-17                                                                            0.167445
Distance(mi)                                                                           0.138149
Accident_Time_10:18:00                                                                 0.131213
Description_Right lane blocked due to crash on I-10 Eastbound at Exit 137 67th Ave.    0.131213
Accident_Time_05:58:00                                                                 0.131213
ID_A-709018                                                                            0.131213
Name: binary_target, dtype: float64


In [11]:
# Only keep Description, Street and Distance (mi) and severity columns
df = df[['Description', 'Street', 'Distance(mi)', 'Severity']]

# Drop rows with missing values
df.dropna(inplace=True)

# Create labels and features
y = df['Severity']
X = df.drop(columns=['Severity'])

# Identify non-numeric columns
non_numeric_columns = X.select_dtypes(include=['object']).columns

# One-hot encode categorical columns
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Instantiate and fit the Logistic Regression model
clf = LogisticRegression(random_state=1, max_iter=1000)
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Combine classes into binary categories
df['binary_target'] = df['Severity'].apply(lambda x: 0 if x in [1, 2] else 1)

# Features and new binary target
X = df.drop(columns=['Severity', 'binary_target'])
y = df['binary_target']

# One-hot encode categorical columns again
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train the logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

[[  0   2   0   0]
 [  0 174   0   0]
 [  0   9   2   0]
 [  0   2   0   0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.93      1.00      0.96       174
           3       1.00      0.18      0.31        11
           4       0.00      0.00      0.00         2

    accuracy                           0.93       189
   macro avg       0.48      0.30      0.32       189
weighted avg       0.91      0.93      0.91       189

Confusion Matrix:
 [[211   0]
 [ 16   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      1.00      0.96       211
           1       0.00      0.00      0.00        16

    accuracy                           0.93       227
   macro avg       0.46      0.50      0.48       227
weighted avg       0.86      0.93      0.90       227

