In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression



# Load the dataset
file_path = 'Resources/US_Accidents_2022_Phoenix_Metro2.csv'
df = pd.read_csv(file_path, low_memory=False)

# Drop columns with too many missing values
df.drop(columns=['End_Lat', 'End_Lng'], inplace=True)

# Handle missing values in other columns
df.dropna(inplace=True)

# Convert date columns to datetime and then to numerical values (e.g., ordinal)
df['Accident_Date'] = pd.to_datetime(df['Accident_Date']).map(pd.Timestamp.toordinal)

# Create labels and features
y = df['Severity']
X = df.drop(columns=['Severity'])

# Identify non-numeric columns
non_numeric_columns = X.select_dtypes(include=['object']).columns

# One-hot encode categorical columns
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Instantiate and fit the Logistic Regression model
clf = LogisticRegression(random_state=1, max_iter=1000)
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Combine classes into binary categories
df['binary_target'] = df['Severity'].apply(lambda x: 0 if x in [1, 2] else 1)

# Features and new binary target
X = df.drop(columns=['Severity', 'binary_target'])
y = df['binary_target']

# One-hot encode categorical columns again
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train the logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)


[[  0   2   0   0]
 [  0 174   0   0]
 [  0  11   0   0]
 [  0   2   0   0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.92      1.00      0.96       174
           3       0.00      0.00      0.00        11
           4       0.00      0.00      0.00         2

    accuracy                           0.92       189
   macro avg       0.23      0.25      0.24       189
weighted avg       0.85      0.92      0.88       189

Confusion Matrix:
 [[210   1]
 [ 16   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      1.00      0.96       211
           1       0.00      0.00      0.00        16

    accuracy                           0.93       227
   macro avg       0.46      0.50      0.48       227
weighted avg       0.86      0.93      0.89       227



In [2]:
from imblearn.over_sampling import SMOTE

# Load the dataset
file_path = 'Resources/US_Accidents_2022_Phoenix_Metro2.csv'
df = pd.read_csv(file_path, low_memory=False)

# Drop columns with too many missing values
df.drop(columns=['End_Lat', 'End_Lng'], inplace=True)

# Handle missing values in other columns
df.dropna(inplace=True)

# Convert date columns to datetime and then to numerical values (e.g., ordinal)
df['Accident_Date'] = pd.to_datetime(df['Accident_Date']).map(pd.Timestamp.toordinal)

# Combine classes into binary categories
df['binary_target'] = df['Severity'].apply(lambda x: 0 if x in [1, 2] else 1)

# Create labels and features
y = df['binary_target']
X = df.drop(columns=['Severity', 'binary_target'])

# Identify non-numeric columns
non_numeric_columns = X.select_dtypes(include=['object']).columns

# One-hot encode categorical columns
X = pd.get_dummies(X, columns=non_numeric_columns, drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Apply SMOTE to balance the classes
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Train the logistic regression model with class weights
model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_smote, y_train_smote)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Confusion Matrix:
 [[210   1]
 [ 16   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      1.00      0.96       211
           1       0.00      0.00      0.00        16

    accuracy                           0.93       227
   macro avg       0.46      0.50      0.48       227
weighted avg       0.86      0.93      0.89       227

